# Train LightGBM v1 cho Steam Hybrid Recommendation trên Google Colab

Notebook này dùng để train LightGBM v1 từ dữ liệu Parquet đã export ra GCS.

Thiết kế chính:
- Không dùng `pd.read_parquet()` full bảng nếu dễ tràn RAM.
- Đọc Parquet theo batch bằng PyArrow.
- Ghi feature vào `numpy.memmap` trên ổ đĩa Colab.
- Train LightGBM CPU.
- Lưu model, metrics, feature importance vào Google Drive.

Bạn chỉ cần sửa `GCS_PREFIX` nếu folder export khác.

In [ ]:
# =========================================
# 1. Install libraries
# =========================================
!pip install -q lightgbm pyarrow gcsfs scikit-learn pandas matplotlib

In [ ]:
# =========================================
# 2. Authenticate Google Cloud
# =========================================
from google.colab import auth
auth.authenticate_user()

PROJECT_ID = "project-79499e5c-69d7-42b8-864"
BUCKET = "truong_bigdata_24032026_init"

print("PROJECT_ID:", PROJECT_ID)
print("BUCKET:", BUCKET)

PROJECT_ID: project-79499e5c-69d7-42b8-864
BUCKET: truong_bigdata_24032026_init

In [ ]:
# =========================================
# 3. Mount Google Drive for output
# =========================================
from google.colab import drive
drive.mount("/content/drive")

import os

DRIVE_OUT_DIR = "/content/drive/MyDrive/Steam_Hybrid_Recommender_Demo"
os.makedirs(DRIVE_OUT_DIR, exist_ok=True)

print("Output folder:", DRIVE_OUT_DIR)

Mounted at /content/drive
Output folder: /content/drive/MyDrive/Steam_Hybrid_Recommender_Demo

In [ ]:
# =========================================
# 4. Imports and GCS path config
# =========================================
import os
import gc
import json
import numpy as np
import pandas as pd
import gcsfs
import pyarrow.parquet as pq
import lightgbm as lgb
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, average_precision_score, log_loss

# Folder chứa các file parquet numeric-only đã export từ BigQuery
# Không thêm gs:// ở đầu trong GCS_PREFIX vì gcsfs dùng dạng bucket/path
GCS_PREFIX = "truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/"

# Nếu folder của bạn khác, sửa dòng trên.
print("GCS_PREFIX:", GCS_PREFIX)

GCS_PREFIX: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/

In [ ]:
# =========================================
# 5. Feature columns
# =========================================

# ID cols chỉ cần nếu bạn muốn đọc lại để predict/rank sau train.
# Khi train memmap để tránh RAM, ta KHÔNG đọc id_cols.
id_cols = ["user_id", "app_id", "user_idx", "app_idx"]
target_col = "label"

# Bộ feature basic, đủ mạnh để train v1 và nhẹ RAM hơn.
feature_cols = [
    "als_score",
    "als_rank",
    "als_inverse_rank",
    "als_rank_log",

    "language_score",
    "has_language_match",
    "matched_language_count",

    "user_activity_score",
    "user_weight",
    "user_reviews_log",
    "user_products_log",

    "platform_score",
    "steam_deck_score",

    "positive_ratio",
    "positive_review_share",
    "review_count_final",
    "avg_recommendation_hours",

    "price_final_clean",
    "discount",
    "is_free",

    "quality_score",
    "popularity_score",
    "engagement_score",
    "price_attractiveness_score",
    "recency_score",
    "game_profile_score",

    "als_x_language_score",
    "als_x_popularity_score",
    "als_x_quality_score",
    "user_activity_x_game_engagement",
]

all_cols = [target_col] + feature_cols

print("Number of features:", len(feature_cols))
print(feature_cols)

Number of features: 30
['als_score', 'als_rank', 'als_inverse_rank', 'als_rank_log', 'language_score', 'has_language_match', 'matched_language_count', 'user_activity_score', 'user_weight', 'user_reviews_log', 'user_products_log', 'platform_score', 'steam_deck_score', 'positive_ratio', 'positive_review_share', 'review_count_final', 'avg_recommendation_hours', 'price_final_clean', 'discount', 'is_free', 'quality_score', 'popularity_score', 'engagement_score', 'price_attractiveness_score', 'recency_score', 'game_profile_score', 'als_x_language_score', 'als_x_popularity_score', 'als_x_quality_score', 'user_activity_x_game_engagement']

In [ ]:
# =========================================
# 6. List parquet files on GCS
# =========================================
fs = gcsfs.GCSFileSystem(project=PROJECT_ID)

parquet_files = fs.glob(GCS_PREFIX + "*.parquet")
if len(parquet_files) == 0:
    parquet_files = fs.glob(GCS_PREFIX + "**/*.parquet")

print("Found parquet files:", len(parquet_files))
for f in parquet_files[:10]:
    print(f)

if len(parquet_files) == 0:
    raise FileNotFoundError(f"No parquet files found under gs://{GCS_PREFIX}")

Found parquet files: 167
truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000000.parquet
truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000001.parquet
truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000002.parquet
truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000003.parquet
truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000004.parquet
truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000005.parquet
truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000006.parquet
truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000007.parquet
truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000008.parquet
truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000009.parquet

In [ ]:
# =========================================
# 7. Check schema of first parquet file
# =========================================
with fs.open(parquet_files[0], "rb") as file_obj:
    pf = pq.ParquetFile(file_obj)
    print("Rows in first file:", pf.metadata.num_rows)
    print("Columns in first file:")
    print(pf.schema)

# Check missing expected columns
with fs.open(parquet_files[0], "rb") as file_obj:
    pf = pq.ParquetFile(file_obj)
    available_cols = set(pf.schema.names)

missing_cols = [c for c in all_cols if c not in available_cols]
print("Missing cols:", missing_cols)

if missing_cols:
    raise ValueError("Some required columns are missing. Check export SQL or feature_cols list.")

Rows in first file: 100800
Columns in first file:
<pyarrow._parquet.ParquetSchema object at 0x7877cf72c740>
required group field_id=-1 schema {
  optional int64 field_id=-1 user_id;
  optional int64 field_id=-1 app_id;
  optional int64 field_id=-1 user_idx;
  optional int64 field_id=-1 app_idx;
  optional int64 field_id=-1 label;
  optional double field_id=-1 als_score;
  optional int64 field_id=-1 als_rank;
  optional double field_id=-1 als_inverse_rank;
  optional double field_id=-1 als_rank_log;
  optional double field_id=-1 user_products_raw;
  optional double field_id=-1 user_reviews_raw;
  optional double field_id=-1 user_products_owned;
  optional double field_id=-1 user_reviews_count;
  optional double field_id=-1 user_products_log;
  optional double field_id=-1 user_reviews_log;
  optional double field_id=-1 user_review_density;
  optional double field_id=-1 user_activity_score;
  optional double field_id=-1 user_weight;
  optional int64 field_id=-1 user_has_enough_signal;
  optional int64 field_id=-1 user_is_outlier;
  optional int64 field_id=-1 days_since_release;
  optional int64 field_id=-1 game_win;
  optional int64 field_id=-1 game_mac;
  optional int64 field_id=-1 game_linux;
  optional int64 field_id=-1 platform_count;
  optional int64 field_id=-1 is_cross_platform;
  optional double field_id=-1 platform_score;
  optional int64 field_id=-1 steam_deck;
  optional double field_id=-1 steam_deck_score;
  optional double field_id=-1 game_rating;
  optional double field_id=-1 positive_ratio;
  optional double field_id=-1 positive_review_share;
  optional double field_id=-1 user_reviews;
  optional double field_id=-1 user_reviews_final;
  optional double field_id=-1 review_count_all_reviews;
  optional double field_id=-1 review_count_final;
  optional double field_id=-1 positive_review_count;
  optional double field_id=-1 negative_review_count;
  optional double field_id=-1 recommendation_event_count;
  optional double field_id=-1 recommendation_event_count_final;
  optional double field_id=-1 avg_recommendation_hours;
  optional double field_id=-1 avg_helpful;
  optional double field_id=-1 avg_funny;
  optional double field_id=-1 recommended_count;
  optional double field_id=-1 price_final;
  optional double field_id=-1 price_original;
  optional double field_id=-1 price_final_clean;
  optional double field_id=-1 price_original_clean;
  optional double field_id=-1 discount;
  optional int64 field_id=-1 is_free;
  optional double field_id=-1 quality_score;
  optional double field_id=-1 popularity_score;
  optional double field_id=-1 engagement_score;
  optional double field_id=-1 price_attractiveness_score;
  optional double field_id=-1 recency_score;
  optional double field_id=-1 game_profile_score;
  optional double field_id=-1 language_score;
  optional int64 field_id=-1 has_language_match;
  optional int64 field_id=-1 matched_language_count;
  optional int64 field_id=-1 matched_user_review_count;
  optional int64 field_id=-1 matched_game_review_count;
  optional double field_id=-1 max_single_language_match_score;
  optional double field_id=-1 als_x_language_score;
  optional double field_id=-1 als_x_popularity_score;
  optional double field_id=-1 als_x_quality_score;
  optional double field_id=-1 user_activity_x_game_engagement;
}

Missing cols: []

In [ ]:
# =========================================
# 8. Count total rows without loading full data
# =========================================
total_rows = 0
for i, f in enumerate(parquet_files, start=1):
    with fs.open(f, "rb") as file_obj:
        pf = pq.ParquetFile(file_obj)
        total_rows += pf.metadata.num_rows
    if i % 20 == 0:
        print(f"Checked {i}/{len(parquet_files)} files, rows so far: {total_rows:,}")

n_rows = total_rows
n_features = len(feature_cols)

print("Total rows:", f"{n_rows:,}")
print("Number of features:", n_features)

Checked 20/167 files, rows so far: 2,017,286
Checked 40/167 files, rows so far: 4,034,123
Checked 60/167 files, rows so far: 6,051,770
Checked 80/167 files, rows so far: 8,069,185
Checked 100/167 files, rows so far: 10,086,619
Checked 120/167 files, rows so far: 12,106,755
Checked 140/167 files, rows so far: 14,123,852
Checked 160/167 files, rows so far: 16,140,767
Total rows: 16,846,271
Number of features: 30

In [ ]:
# =========================================
# 9. Optional: quick sample read to verify data
# =========================================
with fs.open(parquet_files[0], "rb") as file_obj:
    pf = pq.ParquetFile(file_obj)
    batch = next(pf.iter_batches(batch_size=5, columns=all_cols))
    sample_df = batch.to_pandas()

display(sample_df)
print(sample_df.dtypes)

,label,als_score,als_rank,als_inverse_rank,als_rank_log,language_score,has_language_match,matched_language_count,user_activity_score,user_weight,...,quality_score,popularity_score,engagement_score,price_attractiveness_score,recency_score,game_profile_score,als_x_language_score,als_x_popularity_score,als_x_quality_score,user_activity_x_game_engagement
0,0,0.427105,45,0.022222,3.828641,0.331426,1,1,0.0,1.0,...,0.3395,0.050172,0.022577,0.6375,0.1,0.29153,0.141554,0.021429,0.145002,0.0
1,0,0.429173,37,0.027027,3.637586,0.331426,1,1,0.0,1.0,...,0.3395,0.050172,0.022577,0.6375,0.1,0.29153,0.142239,0.021532,0.145704,0.0
2,0,0.451150,35,0.028571,3.583519,0.331426,1,1,0.0,1.0,...,0.3395,0.050172,0.022577,0.6375,0.1,0.29153,0.149523,0.022635,0.153165,0.0
3,0,0.745587,16,0.062500,2.833213,0.331426,1,1,0.0,1.0,...,0.3395,0.050172,0.022577,0.6375,0.1,0.29153,0.247107,0.037407,0.253127,0.0
4,0,0.638949,32,0.031250,3.496508,0.331426,1,1,0.0,1.0,...,0.3395,0.050172,0.022577,0.6375,0.1,0.29153,0.211764,0.032057,0.216923,0.0

label                                int64
als_score                          float64
als_rank                             int64
als_inverse_rank                   float64
als_rank_log                       float64
language_score                     float64
has_language_match                   int64
matched_language_count               int64
user_activity_score                float64
user_weight                        float64
user_reviews_log                   float64
user_products_log                  float64
platform_score                     float64
steam_deck_score                   float64
positive_ratio                     float64
positive_review_share              float64
review_count_final                 float64
avg_recommendation_hours           float64
price_final_clean                  float64
discount                           float64
is_free                              int64
quality_score                      float64
popularity_score                   float64
engagement_score                   float64
price_attractiveness_score         float64
recency_score                      float64
game_profile_score                 float64
als_x_language_score               float64
als_x_popularity_score             float64
als_x_quality_score                float64
user_activity_x_game_engagement    float64
dtype: object

In [ ]:
# =========================================
# 10. Create numpy memmap files on Colab disk
# =========================================
MEMMAP_DIR = "/content/lgbm_memmap"
os.makedirs(MEMMAP_DIR, exist_ok=True)

X_path = f"{MEMMAP_DIR}/X_float32.dat"
y_path = f"{MEMMAP_DIR}/y_int8.dat"

# X: float32 feature matrix
# y: int8 label vector
X_mm = np.memmap(
    X_path,
    dtype="float32",
    mode="w+",
    shape=(n_rows, n_features)
)

y_mm = np.memmap(
    y_path,
    dtype="int8",
    mode="w+",
    shape=(n_rows,)
)

print("Memmap created:")
print("X:", X_mm.shape, X_mm.dtype)
print("y:", y_mm.shape, y_mm.dtype)
print("X file:", X_path)
print("y file:", y_path)

Memmap created:
X: (16846271, 30) float32
y: (16846271,) int8
X file: /content/lgbm_memmap/X_float32.dat
y file: /content/lgbm_memmap/y_int8.dat

In [ ]:
# =========================================
# 11. Read parquet by batches and write into memmap
# =========================================
# Nếu RAM vẫn căng, giảm batch_size xuống 100_000 hoặc 50_000
batch_size = 100_000
row_cursor = 0

for file_idx, f in enumerate(parquet_files, start=1):
    print(f"\n[{file_idx}/{len(parquet_files)}] Reading: {f}")

    with fs.open(f, "rb") as file_obj:
        pf = pq.ParquetFile(file_obj)

        for batch in pf.iter_batches(batch_size=batch_size, columns=all_cols):
            pdf = batch.to_pandas()

            # Label
            y_batch = (
                pd.to_numeric(pdf[target_col], errors="coerce")
                .fillna(0)
                .astype("int8")
                .to_numpy()
            )

            # Feature matrix: convert each column to float32, fill NaN/inf
            X_cols = []
            for c in feature_cols:
                arr = pd.to_numeric(pdf[c], errors="coerce").astype("float32").to_numpy()
                arr = np.nan_to_num(arr, nan=0.0, posinf=0.0, neginf=0.0).astype("float32")
                X_cols.append(arr)

            X_batch = np.column_stack(X_cols).astype("float32")
            n = len(pdf)

            X_mm[row_cursor:row_cursor+n, :] = X_batch
            y_mm[row_cursor:row_cursor+n] = y_batch

            row_cursor += n

            del pdf, X_batch, X_cols, y_batch, batch
            gc.collect()

    X_mm.flush()
    y_mm.flush()
    print("Rows loaded so far:", f"{row_cursor:,}")

print("\nDone.")
print("Total loaded rows:", f"{row_cursor:,}")

if row_cursor != n_rows:
    print("WARNING: loaded row count differs from metadata row count.")

[1/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000000.parquet
Rows loaded so far: 100,800

[2/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000001.parquet
Rows loaded so far: 201,513

[3/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000002.parquet
Rows loaded so far: 302,656

[4/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000003.parquet
Rows loaded so far: 403,430

[5/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000004.parquet
Rows loaded so far: 504,110

[6/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000005.parquet
Rows loaded so far: 605,342

[7/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000006.parquet
Rows loaded so far: 706,425

[8/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000007.parquet
Rows loaded so far: 807,183

[9/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000008.parquet
Rows loaded so far: 907,789

[10/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000009.parquet
Rows loaded so far: 1,008,849

[11/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000010.parquet
Rows loaded so far: 1,109,579

[12/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000011.parquet
Rows loaded so far: 1,210,842

[13/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000012.parquet
Rows loaded so far: 1,311,151

[14/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000013.parquet
Rows loaded so far: 1,412,252

[15/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000014.parquet
Rows loaded so far: 1,513,374

[16/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000015.parquet
Rows loaded so far: 1,613,856

[17/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000016.parquet
Rows loaded so far: 1,714,260

[18/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000017.parquet
Rows loaded so far: 1,815,481

[19/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000018.parquet
Rows loaded so far: 1,916,235

[20/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000019.parquet
Rows loaded so far: 2,017,286

[21/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000020.parquet
Rows loaded so far: 2,118,217

[22/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000021.parquet
Rows loaded so far: 2,218,965

[23/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000022.parquet
Rows loaded so far: 2,319,531

[24/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000023.parquet
Rows loaded so far: 2,420,183

[25/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000024.parquet
Rows loaded so far: 2,521,046

[26/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000025.parquet
Rows loaded so far: 2,621,961

[27/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000026.parquet
Rows loaded so far: 2,722,877

[28/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000027.parquet
Rows loaded so far: 2,823,855

[29/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000028.parquet
Rows loaded so far: 2,924,606

[30/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000029.parquet
Rows loaded so far: 3,025,516

[31/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000030.parquet
Rows loaded so far: 3,126,696

[32/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000031.parquet
Rows loaded so far: 3,227,855

[33/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000032.parquet
Rows loaded so far: 3,328,471

[34/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000033.parquet
Rows loaded so far: 3,428,846

[35/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000034.parquet
Rows loaded so far: 3,529,807

[36/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000035.parquet
Rows loaded so far: 3,630,724

[37/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000036.parquet
Rows loaded so far: 3,731,163

[38/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000037.parquet
Rows loaded so far: 3,831,511

[39/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000038.parquet
Rows loaded so far: 3,932,914

[40/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000039.parquet
Rows loaded so far: 4,034,123

[41/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000040.parquet
Rows loaded so far: 4,135,464

[42/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000041.parquet
Rows loaded so far: 4,236,396

[43/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000042.parquet
Rows loaded so far: 4,336,948

[44/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000043.parquet
Rows loaded so far: 4,438,020

[45/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000044.parquet
Rows loaded so far: 4,538,465

[46/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000045.parquet
Rows loaded so far: 4,639,332

[47/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000046.parquet
Rows loaded so far: 4,740,056

[48/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000047.parquet
Rows loaded so far: 4,840,880

[49/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000048.parquet
Rows loaded so far: 4,941,944

[50/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000049.parquet
Rows loaded so far: 5,043,401

[51/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000050.parquet
Rows loaded so far: 5,144,061

[52/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000051.parquet
Rows loaded so far: 5,245,389

[53/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000052.parquet
Rows loaded so far: 5,345,719

[54/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000053.parquet
Rows loaded so far: 5,447,017

[55/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000054.parquet
Rows loaded so far: 5,548,176

[56/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000055.parquet
Rows loaded so far: 5,648,566

[57/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000056.parquet
Rows loaded so far: 5,749,381

[58/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000057.parquet
Rows loaded so far: 5,850,271

[59/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000058.parquet
Rows loaded so far: 5,951,409

[60/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000059.parquet
Rows loaded so far: 6,051,770

[61/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000060.parquet
Rows loaded so far: 6,152,863

[62/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000061.parquet
Rows loaded so far: 6,253,008

[63/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000062.parquet
Rows loaded so far: 6,354,271

[64/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000063.parquet
Rows loaded so far: 6,454,690

[65/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000064.parquet
Rows loaded so far: 6,555,421

[66/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000065.parquet
Rows loaded so far: 6,656,281

[67/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000066.parquet
Rows loaded so far: 6,757,183

[68/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000067.parquet
Rows loaded so far: 6,857,934

[69/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000068.parquet
Rows loaded so far: 6,958,815

[70/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000069.parquet
Rows loaded so far: 7,059,533

[71/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000070.parquet
Rows loaded so far: 7,160,987

[72/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000071.parquet
Rows loaded so far: 7,261,850

[73/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000072.parquet
Rows loaded so far: 7,362,636

[74/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000073.parquet
Rows loaded so far: 7,463,859

[75/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000074.parquet
Rows loaded so far: 7,564,423

[76/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000075.parquet
Rows loaded so far: 7,665,609

[77/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000076.parquet
Rows loaded so far: 7,766,639

[78/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000077.parquet
Rows loaded so far: 7,867,625

[79/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000078.parquet
Rows loaded so far: 7,968,310

[80/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000079.parquet
Rows loaded so far: 8,069,185

[81/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000080.parquet
Rows loaded so far: 8,170,397

[82/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000081.parquet
Rows loaded so far: 8,271,129

[83/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000082.parquet
Rows loaded so far: 8,371,758

[84/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000083.parquet
Rows loaded so far: 8,472,312

[85/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000084.parquet
Rows loaded so far: 8,573,922

[86/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000085.parquet
Rows loaded so far: 8,674,336

[87/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000086.parquet
Rows loaded so far: 8,775,874

[88/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000087.parquet
Rows loaded so far: 8,876,274

[89/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000088.parquet
Rows loaded so far: 8,976,701

[90/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000089.parquet
Rows loaded so far: 9,077,909

[91/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000090.parquet
Rows loaded so far: 9,178,227

[92/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000091.parquet
Rows loaded so far: 9,279,133

[93/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000092.parquet
Rows loaded so far: 9,380,186

[94/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000093.parquet
Rows loaded so far: 9,480,955

[95/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000094.parquet
Rows loaded so far: 9,582,070

[96/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000095.parquet
Rows loaded so far: 9,682,662

[97/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000096.parquet
Rows loaded so far: 9,783,904

[98/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000097.parquet
Rows loaded so far: 9,884,880

[99/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000098.parquet
Rows loaded so far: 9,985,777

[100/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000099.parquet
Rows loaded so far: 10,086,619

[101/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000100.parquet
Rows loaded so far: 10,187,295

[102/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000101.parquet
Rows loaded so far: 10,288,052

[103/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000102.parquet
Rows loaded so far: 10,389,302

[104/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000103.parquet
Rows loaded so far: 10,490,204

[105/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000104.parquet
Rows loaded so far: 10,590,701

[106/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000105.parquet
Rows loaded so far: 10,692,277

[107/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000106.parquet
Rows loaded so far: 10,793,365

[108/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000107.parquet
Rows loaded so far: 10,894,872

[109/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000108.parquet
Rows loaded so far: 10,996,355

[110/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000109.parquet
Rows loaded so far: 11,096,980

[111/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000110.parquet
Rows loaded so far: 11,198,266

[112/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000111.parquet
Rows loaded so far: 11,298,870

[113/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000112.parquet
Rows loaded so far: 11,399,560

[114/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000113.parquet
Rows loaded so far: 11,500,656

[115/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000114.parquet
Rows loaded so far: 11,601,464

[116/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000115.parquet
Rows loaded so far: 11,703,194

[117/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000116.parquet
Rows loaded so far: 11,804,123

[118/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000117.parquet
Rows loaded so far: 11,905,319

[119/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000118.parquet
Rows loaded so far: 12,005,417

[120/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000119.parquet
Rows loaded so far: 12,106,755

[121/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000120.parquet
Rows loaded so far: 12,207,563

[122/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000121.parquet
Rows loaded so far: 12,308,580

[123/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000122.parquet
Rows loaded so far: 12,409,937

[124/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000123.parquet
Rows loaded so far: 12,510,961

[125/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000124.parquet
Rows loaded so far: 12,612,122

[126/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000125.parquet
Rows loaded so far: 12,712,926

[127/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000126.parquet
Rows loaded so far: 12,813,863

[128/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000127.parquet
Rows loaded so far: 12,914,234

[129/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000128.parquet
Rows loaded so far: 13,015,048

[130/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000129.parquet
Rows loaded so far: 13,115,831

[131/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000130.parquet
Rows loaded so far: 13,216,775

[132/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000131.parquet
Rows loaded so far: 13,317,314

[133/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000132.parquet
Rows loaded so far: 13,417,482

[134/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000133.parquet
Rows loaded so far: 13,518,378

[135/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000134.parquet
Rows loaded so far: 13,619,242

[136/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000135.parquet
Rows loaded so far: 13,719,969

[137/167] Reading: truong_bigdata_24032026_init/steam/gold/lgbm_train_features_v1_16m_numeric/000000000136.parquet
Rows loaded so far: 13,821,202


In [ ]:
# =========================================
# 12. Reopen memmap as read-only and inspect label distribution
# =========================================
X = np.memmap(
    X_path,
    dtype="float32",
    mode="r",
    shape=(n_rows, n_features)
)

y = np.memmap(
    y_path,
    dtype="int8",
    mode="r",
    shape=(n_rows,)
)

print("X:", X.shape, X.dtype)
print("y:", y.shape, y.dtype)
print("Positive rows:", int(y.sum()))
print("Negative rows:", int(len(y) - y.sum()))
print("Positive rate:", float(y.mean()))

X: (16846271, 30) float32
y: (16846271,) int8
Positive rows: 1425281
Negative rows: 15420990
Positive rate: 0.08460513308850368

In [ ]:
# =========================================
# 13. Create train/valid split
# =========================================
# Lưu ý: np.asarray(y) tạo vector label trong RAM, nhưng y chỉ int8 nên ~16MB cho 16M rows, ổn.
indices = np.arange(n_rows)

train_idx, valid_idx = train_test_split(
    indices,
    test_size=0.15,
    random_state=42,
    stratify=np.asarray(y)
)

print("Train rows:", f"{len(train_idx):,}")
print("Valid rows:", f"{len(valid_idx):,}")

Train rows: 14,319,330
Valid rows: 2,526,941

In [ ]:
# =========================================
# 14. Materialize train/valid arrays
# =========================================
# Bước này copy X_train, X_valid vào RAM.
# Với 16M x 30 float32, thường khoảng ~1.9GB trước overhead, có thể chấp nhận trên Colab RAM cao.
# Nếu vẫn tràn RAM, xem cell fallback phía dưới.

try:
    X_train = X[train_idx]
    y_train = y[train_idx]

    X_valid = X[valid_idx]
    y_valid = y[valid_idx]

    print("X_train:", X_train.shape, X_train.dtype)
    print("X_valid:", X_valid.shape, X_valid.dtype)
    print("Train positive rate:", float(y_train.mean()))
    print("Valid positive rate:", float(y_valid.mean()))
except MemoryError:
    print("MemoryError: Không đủ RAM để materialize train/valid.")
    raise

X_train: (14319330, 30) float32
X_valid: (2526941, 30) float32
Train positive rate: 0.08460514563181377
Valid positive rate: 0.08460506200975805

In [ ]:
# =========================================
# 15. Train LightGBM CPU - fixed version
# =========================================
import lightgbm as lgb
import numpy as np
import pandas as pd
import gc
import os

num_pos = int(y_train.sum())
num_neg = int(len(y_train) - num_pos)
scale_pos_weight = num_neg / max(num_pos, 1)

print("num_pos:", f"{num_pos:,}")
print("num_neg:", f"{num_neg:,}")
print("scale_pos_weight:", scale_pos_weight)

# Ép kiểu để giảm RAM
X_train = X_train.astype(np.float32)
X_valid = X_valid.astype(np.float32)
y_train = y_train.astype(np.int8)
y_valid = y_valid.astype(np.int8)

# Kiểm tra nhanh NaN / Inf
print("X_train shape:", X_train.shape)
print("X_valid shape:", X_valid.shape)

print("Train positive rate:", y_train.mean())
print("Valid positive rate:", y_valid.mean())

params = {
    "objective": "binary",

    # Đặt average_precision lên trước để early stopping ưu tiên PR-AUC
    # Vì bài recommend/ranking lệch nhãn, AP quan trọng hơn logloss
    "metric": ["average_precision", "auc"],

    "boosting_type": "gbdt",
    "learning_rate": 0.03,
    "num_leaves": 31,
    "max_depth": -1,
    "min_data_in_leaf": 200,

    "feature_fraction": 0.8,
    "bagging_fraction": 0.8,
    "bagging_freq": 1,

    "lambda_l1": 0.0,
    "lambda_l2": 1.0,

    # Không hard-code, dùng đúng tỷ lệ train hiện tại
    "scale_pos_weight": scale_pos_weight,

    # Tối ưu cho CPU / Colab
    "force_col_wise": True,
    "num_threads": os.cpu_count(),

    "verbosity": -1,
    "seed": 42,
    "feature_fraction_seed": 42,
    "bagging_seed": 42,
    "data_random_seed": 42,
}

train_data = lgb.Dataset(
    X_train,
    label=y_train,
    feature_name=feature_cols,
    free_raw_data=True
)

valid_data = lgb.Dataset(
    X_valid,
    label=y_valid,
    feature_name=feature_cols,
    reference=train_data,
    free_raw_data=True
)

model = lgb.train(
    params,
    train_data,
    valid_sets=[valid_data],
    valid_names=["valid"],
    num_boost_round=500,
    callbacks=[
        # Quan trọng: chỉ dùng metric đầu tiên = average_precision để early stopping
        lgb.early_stopping(
            stopping_rounds=50,
            first_metric_only=True,
            verbose=True
        ),
        lgb.log_evaluation(period=20),
    ],
)

print("=" * 80)
print("Best iteration:", model.best_iteration)
print("Best score:", model.best_score)
print("=" * 80)

gc.collect()

num_pos: 1,211,489
num_neg: 13,107,841
scale_pos_weight: 10.819612064162365
X_train shape: (14319330, 30)
X_valid shape: (2526941, 30)
Train positive rate: 0.08460514563181377
Valid positive rate: 0.08460506200975805
Training until validation scores don't improve for 50 rounds
[20]	valid's average_precision: 0.205171	valid's auc: 0.711096
[40]	valid's average_precision: 0.207093	valid's auc: 0.713588
[60]	valid's average_precision: 0.208599	valid's auc: 0.715862
[80]	valid's average_precision: 0.210782	valid's auc: 0.718116
[100]	valid's average_precision: 0.212373	valid's auc: 0.72024
[120]	valid's average_precision: 0.213739	valid's auc: 0.721992
[140]	valid's average_precision: 0.215053	valid's auc: 0.723652
[160]	valid's average_precision: 0.21625	valid's auc: 0.724834
[180]	valid's average_precision: 0.217397	valid's auc: 0.725789
[200]	valid's average_precision: 0.218335	valid's auc: 0.726565
[220]	valid's average_precision: 0.219138	valid's auc: 0.727199
[240]	valid's average_precision: 0.219741	valid's auc: 0.727737
[260]	valid's average_precision: 0.220216	valid's auc: 0.728234
[280]	valid's average_precision: 0.220679	valid's auc: 0.728678
[300]	valid's average_precision: 0.221011	valid's auc: 0.72912
[320]	valid's average_precision: 0.221344	valid's auc: 0.729492
[340]	valid's average_precision: 0.221688	valid's auc: 0.729853
[360]	valid's average_precision: 0.221915	valid's auc: 0.730156
[380]	valid's average_precision: 0.222226	valid's auc: 0.730445
[400]	valid's average_precision: 0.222458	valid's auc: 0.73071
[420]	valid's average_precision: 0.222634	valid's auc: 0.730972
[440]	valid's average_precision: 0.222846	valid's auc: 0.731238
[460]	valid's average_precision: 0.223038	valid's auc: 0.731441
[480]	valid's average_precision: 0.223189	valid's auc: 0.73165
[500]	valid's average_precision: 0.223341	valid's auc: 0.731853
Did not meet early stopping. Best iteration is:
[500]	valid's average_precision: 0.223341	valid's auc: 0.731853
Evaluated only: average_precision
================================================================================
Best iteration: 500
Best score: defaultdict(<class 'collections.OrderedDict'>, {'valid': OrderedDict({'average_precision': np.float64(0.2233411058560215), 'auc': np.float64(0.731853168367094)})})
================================================================================

453

In [ ]:
# =========================================
# 16. Evaluation metrics
# =========================================
valid_pred = model.predict(X_valid, num_iteration=model.best_iteration)

auc = roc_auc_score(y_valid, valid_pred)
ap = average_precision_score(y_valid, valid_pred)
ll = log_loss(y_valid, valid_pred)

metrics_df = pd.DataFrame([{
    "model": "lightgbm_v1_16m_colab_cpu_memmap",
    "rows": int(n_rows),
    "features": int(len(feature_cols)),
    "best_iteration": int(model.best_iteration),
    "valid_auc": float(auc),
    "valid_average_precision": float(ap),
    "valid_logloss": float(ll),
    "positive_rate": float(y.mean()),
    "scale_pos_weight": float(scale_pos_weight),
}])

display(metrics_df)

metrics_path = f"{DRIVE_OUT_DIR}/metrics_lgbm_v1_16m_colab_cpu_memmap.csv"
metrics_df.to_csv(metrics_path, index=False)

print("Saved metrics:", metrics_path)

,model,rows,features,best_iteration,valid_auc,valid_average_precision,valid_logloss,positive_rate,scale_pos_weight
0,lightgbm_v1_16m_colab_cpu_memmap,16846271,30,500,0.731853,0.223341,0.605243,0.084605,10.819612

Saved metrics: /content/drive/MyDrive/Steam_Hybrid_Recommender_Demo/metrics_lgbm_v1_16m_colab_cpu_memmap.csv

In [ ]:
# =========================================
# 17. Save model and feature importance
# =========================================
model_path = f"{DRIVE_OUT_DIR}/lgbm_v1_16m_colab_cpu_memmap_model.txt"
model.save_model(model_path)

print("Saved model:", model_path)

fi = pd.DataFrame({
    "feature": feature_cols,
    "importance_gain": model.feature_importance(importance_type="gain"),
    "importance_split": model.feature_importance(importance_type="split"),
}).sort_values("importance_gain", ascending=False)

fi_path = f"{DRIVE_OUT_DIR}/feature_importance_lgbm_v1_16m_colab_cpu_memmap.csv"
fi.to_csv(fi_path, index=False)

display(fi.head(30))
print("Saved feature importance:", fi_path)

Saved model: /content/drive/MyDrive/Steam_Hybrid_Recommender_Demo/lgbm_v1_16m_colab_cpu_memmap_model.txt

                            feature  importance_gain  importance_split
0                         als_score     1.580729e+07               765
27           als_x_popularity_score     1.453056e+07               556
28              als_x_quality_score     7.243105e+06               479
25               game_profile_score     3.606365e+06              2613
24                    recency_score     3.228059e+06              2397
4                    language_score     3.034466e+06              2451
17                price_final_clean     2.258011e+06              1498
13                   positive_ratio     1.608950e+06              1540
1                          als_rank     1.470121e+06               850
26             als_x_language_score     4.927767e+05               427
23       price_attractiveness_score     4.051528e+05               291
2                  als_inverse_rank     3.941378e+05               150
20                    quality_score     3.610127e+05               317
19                          is_free     2.329631e+05                71
11                   platform_score     2.226818e+05               326
3                      als_rank_log     8.423450e+04                13
15               review_count_final     6.980487e+04                67
6            matched_language_count     6.005632e+04                71
5                has_language_match     3.341807e+04                22
18                         discount     3.319427e+04                84
21                 popularity_score     9.487198e+03                12
7               user_activity_score     0.000000e+00                 0
12                 steam_deck_score     0.000000e+00                 0
10                user_products_log     0.000000e+00                 0
8                       user_weight     0.000000e+00                 0
9                  user_reviews_log     0.000000e+00                 0
14            positive_review_share     0.000000e+00                 0
16         avg_recommendation_hours     0.000000e+00                 0
22                 engagement_score     0.000000e+00                 0
29  user_activity_x_game_engagement     0.000000e+00                 0

Saved feature importance: /content/drive/MyDrive/Steam_Hybrid_Recommender_Demo/feature_importance_lgbm_v1_16m_colab_cpu_memmap.csv

In [ ]:
# =========================================
# 16. Predict validation
# =========================================
import numpy as np
import pandas as pd
from sklearn.metrics import (
    roc_auc_score,
    average_precision_score,
    log_loss,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report,
)

valid_pred = model.predict(
    X_valid,
    num_iteration=model.best_iteration
)

print("valid_pred min:", valid_pred.min())
print("valid_pred max:", valid_pred.max())
print("valid_pred mean:", valid_pred.mean())
print("valid_pred std:", valid_pred.std())

valid_pred min: 0.02295248958027875
valid_pred max: 0.934033628208657
valid_pred mean: 0.43490372671450306
valid_pred std: 0.178561623502728